name: Docker Build & Release

# Main PRs will build, but not release. Main pushes will build & release unstable tag
# Main tags will build & release latest & semver tag. Everything else will not run. 

on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["main"]
    tags: ['v*']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout source
        uses: actions/checkout@v2.5.0
      -
        name: Set image metadata
        id: tags
        uses: docker/metadata-action@v4.1.1
        with:
          # list of Docker images to use as base name for tags
          images: ghcr.io/${{ github.repository }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=unstable
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}

            ghcr.io/${{ github.repository }}:latest
      -
        name: Login to GHCR
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      -
        name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.tags.outputs.tags }}
          build-args: |
            VCS_URL=${{ github.GITHUB_SERVER_URL }}/${{ github.repository }}
            VCS_REF=${{ github.GITHUB_SHA }}
            BUILD_DATE=${{ github.event.repository.updated_at}}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ github.repository}}:buildcache
          cache-to: type=registry,ref=${{ github.repository }}:buildcache,mode=max
